# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import convenio_pb2 as convenio__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in convenio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConvenioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.validarConvenio = channel.unary_unary(
                '/convenio.ConvenioService/validarConvenio',
                request_serializer=convenio__pb2.ValidarConvenioRequest.SerializeToString,
                response_deserializer=convenio__pb2.ValidarConvenioResponse.FromString,
                _registered_method=True)


class ConvenioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def validarConvenio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConvenioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'validarConvenio': grpc.unary_unary_rpc_method_handler(
                    servicer.validarConvenio,
                    request_deserializer=convenio__pb2.ValidarConvenioRequest.FromString,
                    response_serializer=convenio__pb2.ValidarConvenioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'convenio.ConvenioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('convenio.ConvenioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConvenioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def validarConvenio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/convenio.ConvenioService/validarConvenio',
            convenio__pb2.ValidarConvenioRequest.SerializeToString,
            convenio__pb2.ValidarConvenioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
